export const genreGroups = [
  {
    genre: 'Classic Rock',
    songs: [
      'Abracadabra', 'American Girl', 'Amie', 'Angie',
      'A Horse with No Name', 'Brown Eyed Girl',
      "Can't You See", 'Carolina in My Mind', 'Crazy Little Thing Called Love',
      'Crossroads', 'Desperado', 'Drift Away', 'Eminence Front', 'End of the Line',
      'Fire and Rain', "For What It's Worth", "Free Fallin'",
      'Go Your Own Way', 'Got My Mind Set on You', 'Green River',
      'Hard to Handle', 'Harvest Moon', 'Have You Ever Seen the Rain',
      'Heart of Gold', 'Heartbreak Hotel', 'Hey Hey What Can I Do', 'Honky Tonk Women',
      'Hotel California', 'House of the Rising Sun',
      "I Won't Back Down", 'Into the Mystic',
      "Jumpin' Jack Flash", "Knockin' on Heaven's Door",
      'Kodachrome', 'Layla', 'Learning to Fly', "Lyin' Eyes", "Mary Jane's Last Dance",
      'Me and Julio Down by the Schoolyard', 'Midnight Rider', 'Moondance',
      'Old Time Rock and Roll', 'Paint It Black', "Ramblin' Man", 'Rocky Mountain Way',
      'Proud Mary', "Runnin' Down a Dream", 'Simple Man', 'Southern Cross',
      'Start Me Up', 'Stuck in the Middle with You',
      'Sultans of Swing', 'Sundown', 'Suspicious Minds', "Can't Help Falling in Love",
      'Sweet Home Alabama', 'Thank You', 'The Joker', 'The Weight',
      'Turn the Page', 'Ventura Highway',
      "What's Your Name", 'When the Levee Breaks',
      "Who'll Stop the Rain", 'Wild Horses', 'Wish You Were Here', 'Wonderful Tonight',
    ],
  },
  {
    genre: 'The Beatles',
    songs: [
      'Blackbird', 'Come Together', 'Here Comes the Sun', 'Hey Jude',
      'Let It Be', 'Norwegian Wood', 'Yesterday',
    ],
  },
  {
    genre: '90s / 2000s Rock',
    songs: [
      'Aqueous Transmission', 'Banana Pancakes', 'Better Together', 'Black Hole Sun',
      'Californication', 'Clocks', 'Closing Time', 'Come As You Are', 'Crash Into Me',
      'Daughter', 'Drive', 'Drops of Jupiter',
      'Everlong', 'Flake', 'Good Riddance (Time of Your Life)', "How's It Going to Be",
      'I Am the Highway', "I'm Yours", 'If You Could Only See',
      'Inside Out', 'Iris', 'Island in the Sun', 'Jumper', 'Just Breathe',
      'Learn to Fly', 'Little Talks',
      'Otherside', 'Pardon Me', 'Patience', 'Plush',
      'Riptide', 'Santeria', "Say It Ain't So", 'The Man Who Sold the World',
      'The Scientist', 'The Way',
      'Semi-Charmed Life', 'Shine', 'Skinny Love', 'Someday',
      'Times Like These', 'Two Princes', 'Under the Bridge',
      'Warning', 'What I Got', 'When I Come Around', 'Wonderwall', 'Yellow',
      'Gold on the Ceiling', 'Ho Hey', 'Hold My Hand', 'Tighten Up',
    ],
  },
  {
    genre: '80s',
    songs: [
      "Don't Dream It's Over", "Don't You Forget About Me",
      'Everybody Wants to Rule the World', 'Hurts So Good', 'I Melt with You',
      'Jack and Diane', "Jessie's Girl", 'Losing My Religion', 'Man on the Moon',
      'Message in a Bottle', 'Rock the Casbah', 'Should I Stay or Should I Go',
      'The Power of Love', 'Wanted Dead or Alive', 'What I Like About You',
    ],
  },
  {
    genre: 'Country & Americana',
    songs: [
      "All Your'n", 'Amarillo by Morning', 'Big Iron', "Boot Scootin' Boogie",
      'Chicken Fried', 'Copperhead Road', 'Devil Went Down to Georgia',
      "Fishin' in the Dark", 'Folsom Prison Blues', 'Friends in Low Places',
      'American Pie', 'God Bless the USA', 'Jolene', 'Margaritaville', 'Neon Moon',
      'Nose on the Grindstone', 'On the Road Again', 'Peaceful Easy Feeling',
      'Ring of Fire', 'Sleeping on the Blacktop', 'SOB', 'Something in the Orange',
      'Take It Easy', 'Take Me Home Country Roads', 'Take Me to Church',
      'Tennessee Whiskey', 'Tequila Sunrise', "These Boots Are Made for Walkin'",
      'Thunder Rolls', 'Wagon Wheel', 'Whitehouse Road',
    ],
  },
  {
    genre: 'Blues',
    songs: [
      'All Along the Watchtower', 'Blue on Black',
      'Born Under a Bad Sign', 'Call Me the Breeze', 'Dock of the Bay',
      "Howlin' for You", 'Lonely Boy', 'Pride and Joy', 'Red House',
      'Stormy Monday', 'Sweet Home Chicago', 'The Thrill Is Gone',
    ],
  },
  {
    genre: 'Soul & R&B',
    songs: [
      "Ain't No Sunshine", 'Dancing in the Moonlight', 'Gravity',
      'How Sweet It Is', 'Lean on Me', 'Lovely Day', 'Stand By Me',
      'Superstition', 'Use Me',
    ],
  },
]
