export type Song = { title: string; artist: string }

export const songs: Song[] = [
  { title: '3AM', artist: 'Matchbox Twenty' },
  { title: '867-5309 Jenny', artist: 'Tommy Tutone' },
  { title: 'Abracadabra', artist: 'Steve Miller Band' },
  { title: 'Africa', artist: 'Toto' },
  { title: 'All For You', artist: 'Sister Hazel' },
  { title: 'American Girl', artist: 'Tom Petty & The Heartbreakers' },
  { title: 'Amie', artist: 'Pure Prairie League' },
  { title: 'Angie', artist: 'The Rolling Stones' },
  { title: 'Ball and Chain', artist: 'Social Distortion' },
  { title: 'Beds Are Burning', artist: 'Midnight Oil' },
  { title: 'Big Iron', artist: 'Marty Robbins' },
  { title: 'Black Water', artist: 'The Doobie Brothers' },
  { title: 'Blue on Black', artist: 'Kenny Wayne Shepherd' },
  { title: 'Boot Scootin\' Boogie', artist: 'Brooks & Dunn' },
  { title: 'Boyz in the Hood', artist: 'Dynamite Hack' },
  { title: 'Breathe', artist: 'Pink Floyd' },
  { title: 'Call Me the Breeze', artist: 'Eric Clapton' },
  { title: 'Can\'t Stop', artist: 'Red Hot Chili Peppers' },
  { title: 'Careless Whisper', artist: 'George Michael' },
  { title: 'Chicken Fried', artist: 'Zac Brown Band' },
  { title: 'Come As You Are', artist: 'Nirvana' },
  { title: 'Crazy Little Thing Called Love', artist: 'Queen' },
  { title: 'Crossroads', artist: 'Eric Clapton' },
  { title: 'Dance Hall Days', artist: 'Wang Chung' },
  { title: 'Dancing in the Moonlight', artist: 'King Harvest' },
  { title: 'Don\'t Dream It\'s Over', artist: 'Crowded House' },
  { title: 'Don\'t Stop Believin\'', artist: 'Journey' },
  { title: 'Don\'t Stop', artist: 'Fleetwood Mac' },
  { title: 'Don\'t You Forget About Me', artist: 'Simple Minds' },
  { title: 'Drift Away', artist: 'Dobie Gray' },
  { title: 'Drivin\' My Life Away', artist: 'Eddie Rabbitt' },
  { title: 'Drops of Jupiter', artist: 'Train' },
  { title: 'Eminence Front', artist: 'The Who' },
  { title: 'End of the Line', artist: 'Traveling Wilburys' },
  { title: 'Everybody Wants to Rule the World', artist: 'Tears For Fears' },
  { title: 'Fast Car', artist: 'Tracy Chapman' },
  { title: 'Fishin\' in the Dark', artist: 'Nitty Gritty Dirt Band' },
  { title: 'Folsom Prison Blues', artist: 'Johnny Cash' },
  { title: 'Friends in Low Places', artist: 'Garth Brooks' },
  { title: 'Gimme All Your Lovin\'', artist: 'ZZ Top' },
  { title: 'Give Me One Reason', artist: 'Tracy Chapman' },
  { title: 'God Bless the USA', artist: 'Lee Greenwood' },
  { title: 'Gold on the Ceiling', artist: 'The Black Keys' },
  { title: 'Got My Mind Set on You', artist: 'George Harrison' },
  { title: 'Green River', artist: 'Creedence Clearwater Revival' },
  { title: 'Hard to Handle', artist: 'The Black Crowes' },
  { title: 'Harvest Moon', artist: 'Neil Young' },
  { title: 'Have You Ever Seen the Rain', artist: 'Creedence Clearwater Revival' },
  { title: 'Heartbreak Hotel', artist: 'Elvis Presley' },
  { title: 'Hey Hey What Can I Do', artist: 'Led Zeppelin' },
  { title: 'Hey Jealousy', artist: 'Gin Blossoms' },
  { title: 'Honky Tonk Women', artist: 'The Rolling Stones' },
  { title: 'House of the Rising Sun', artist: 'The Animals' },
  { title: 'How Sweet It Is', artist: 'James Taylor' },
  { title: 'Howlin\' for You', artist: 'The Black Keys' },
  { title: 'How\'s It Going to Be', artist: 'Third Eye Blind' },
  { title: 'Hurt', artist: 'Johnny Cash' },
  { title: 'Hurts So Good', artist: 'John Mellencamp' },
  { title: 'I Melt with You', artist: 'Modern English' },
  { title: 'I Want You to Want Me', artist: 'Cheap Trick' },
  { title: 'If You Could Only See', artist: 'Tonic' },
  { title: 'I\'m Gonna Be (500 Miles)', artist: 'The Proclaimers' },
  { title: 'Inside Out', artist: 'Eve 6' },
  { title: 'Island in the Sun', artist: 'Weezer' },
  { title: 'Jack and Diane', artist: 'John Mellencamp' },
  { title: 'Jackson', artist: 'Johnny Cash & June Carter Cash' },
  { title: 'Jumpin\' Jack Flash', artist: 'The Rolling Stones' },
  { title: 'Kodachrome', artist: 'Paul Simon' },
  { title: 'Lake of Fire', artist: 'Nirvana' },
  { title: 'Last Nite', artist: 'The Strokes' },
  { title: 'Learn to Fly', artist: 'Foo Fighters' },
  { title: 'Learning to Fly', artist: 'Tom Petty & The Heartbreakers' },
  { title: 'Listen to the Music', artist: 'The Doobie Brothers' },
  { title: 'Little Lion Man', artist: 'Mumford & Sons' },
  { title: 'Lonely Boy', artist: 'The Black Keys' },
  { title: 'Lonely is the Night', artist: 'Billy Squier' },
  { title: 'Mary Jane\'s Last Dance', artist: 'Tom Petty & The Heartbreakers' },
  { title: 'Me and Julio Down by the Schoolyard', artist: 'Paul Simon' },
  { title: 'Message in a Bottle', artist: 'The Police' },
  { title: 'Money', artist: 'Pink Floyd' },
  { title: 'Money for Nothing', artist: 'Dire Straits' },
  { title: 'Mother', artist: 'Danzig' },
  { title: 'Mr. Jones', artist: 'Counting Crows' },
  { title: 'My Sharona', artist: 'The Knack' },
  { title: 'Mysterious Ways', artist: 'U2' },
  { title: 'Need You Tonight', artist: 'INXS' },
  { title: 'No Matter What', artist: 'Badfinger' },
  { title: 'Norwegian Wood', artist: 'The Beatles' },
  { title: 'Nose on the Grindstone', artist: 'Tyler Childers' },
  { title: 'I Am a Man of Constant Sorrow', artist: 'Soggy Bottom Boys' },
  { title: 'On a Plain', artist: 'Nirvana' },
  { title: 'Our House', artist: 'Madness' },
  { title: 'Paint It Black', artist: 'The Rolling Stones' },
  { title: 'Pawn Shop', artist: 'Sublime' },
  { title: 'Peaceful Easy Feeling', artist: 'Eagles' },
  { title: 'Picture', artist: 'Kid Rock feat. Sheryl Crow' },
  { title: 'Pride and Joy', artist: 'Stevie Ray Vaughan' },
  { title: 'Proud Mary', artist: 'Creedence Clearwater Revival' },
  { title: 'Psycho Killer', artist: 'Talking Heads' },
  { title: 'Ramblin\' Man', artist: 'The Allman Brothers Band' },
  { title: 'Ring of Fire', artist: 'Johnny Cash' },
  { title: 'Rock the Casbah', artist: 'The Clash' },
  { title: 'Rocky Mountain Way', artist: 'Joe Walsh' },
  { title: 'Runnin\' Down a Dream', artist: 'Tom Petty' },
  { title: 'Say It Ain\'t So', artist: 'Weezer' },
  { title: 'Sharp Dressed Man', artist: 'ZZ Top' },
  { title: 'She Sells Sanctuary', artist: 'The Cult' },
  { title: 'Should I Stay or Should I Go', artist: 'The Clash' },
  { title: 'Sleeping on the Blacktop', artist: 'Colter Wall' },
  { title: 'SOB', artist: 'Nathaniel Rateliff' },
  { title: 'Someday', artist: 'Sugar Ray' },
  { title: 'Something in the Orange', artist: 'Zach Bryan' },
  { title: 'Stacy\'s Mom', artist: 'Fountains of Wayne' },
  { title: 'Start Me Up', artist: 'The Rolling Stones' },
  { title: 'Steady as She Goes', artist: 'The Raconteurs' },
  { title: 'Stuck in the Middle with You', artist: 'Stealers Wheel' },
  { title: 'Summer of \'69', artist: 'Bryan Adams' },
  { title: 'Sunday Bloody Sunday', artist: 'U2' },
  { title: 'Sundown', artist: 'Gordon Lightfoot' },
  { title: 'Sweet Caroline', artist: 'Neil Diamond' },
  { title: 'Shelter Me', artist: 'Tab Benoit' },
  { title: 'Take It Easy', artist: 'Eagles' },
  { title: 'Take Me Home Country Roads', artist: 'John Denver' },
  { title: 'Take on Me', artist: 'a-ha' },
  { title: 'Takin\' Care of Business', artist: 'Bachman-Turner Overdrive' },
  { title: 'Tennessee Whiskey', artist: 'Chris Stapleton' },
  { title: 'Tequila Sunrise', artist: 'Eagles' },
  { title: 'Thank You', artist: 'Led Zeppelin' },
  { title: 'The Man Who Sold the World', artist: 'Nirvana' },
  { title: 'The Middle', artist: 'Jimmy Eat World' },
  { title: 'The Power of Love', artist: 'Huey Lewis & The News' },
  { title: 'The Safety Dance', artist: 'Men Without Hats' },
  { title: 'The Stake', artist: 'Steve Miller Band' },
  { title: 'The Way', artist: 'Fastball' },
  { title: 'The Weight', artist: 'The Band' },
  { title: 'These Boots Are Made for Walkin\'', artist: 'Nancy Sinatra' },
  { title: 'Tighten Up', artist: 'The Black Keys' },
  { title: 'Time Bomb', artist: 'Rancid' },
  { title: 'Time', artist: 'Pink Floyd' },
  { title: 'Two Princes', artist: 'Spin Doctors' },
  { title: 'Unwell', artist: 'Matchbox Twenty' },
  { title: 'Wanted Dead or Alive', artist: 'Bon Jovi' },
  { title: 'What I Like About You', artist: 'The Romantics' },
  { title: 'What\'s Your Name', artist: 'Lynyrd Skynyrd' },
  { title: 'When I Come Around', artist: 'Green Day' },
  { title: 'When the Levee Breaks', artist: 'Led Zeppelin' },
  { title: 'White Wedding', artist: 'Billy Idol' },
  { title: 'Whitehouse Road', artist: 'Tyler Childers' },
  { title: 'Who\'ll Stop the Rain', artist: 'Creedence Clearwater Revival' },
  { title: 'Wild Horses', artist: 'The Rolling Stones' },
  { title: 'Wish You Were Here', artist: 'Pink Floyd' },
  { title: 'You Give Love a Bad Name', artist: 'Bon Jovi' },
  { title: 'You Wreck Me', artist: 'Tom Petty' },
  { title: 'Your Love', artist: 'The Outfield' },
].sort((a, b) => a.title.localeCompare(b.title))
