export type Song = { title: string; artist: string }

export const songs: Song[] = [
  { title: '3AM', artist: 'Matchbox Twenty' },
  { title: 'Jenny Jenny (867-5309)', artist: 'Tommy Tutone' },
  { title: 'Abracadabra', artist: 'Steve Miller Band' },
  { title: 'All For You', artist: 'Sister Hazel' },
  { title: 'American Girl', artist: 'Tom Petty & The Heartbreakers' },
  { title: 'Amie', artist: 'Pure Prairie League' },
  { title: 'Angie', artist: 'The Rolling Stones' },
  { title: 'Ball and Chain', artist: 'Social Distortion' },
  { title: 'Big Iron', artist: 'Marty Robbins' },
  { title: 'Black Water', artist: 'The Doobie Brothers' },
  { title: 'Blue on Black', artist: 'Kenny Wayne Shepherd' },
  { title: 'Boot Scootin\' Boogie', artist: 'Brooks & Dunn' },
  { title: 'Breathe', artist: 'Pink Floyd' },
  { title: 'Call Me the Breeze', artist: 'J.J. Cale' },
  { title: 'Can\'t Stop', artist: 'Red Hot Chili Peppers' },
  { title: 'Chicken Fried', artist: 'Zac Brown Band' },
  { title: 'Come As You Are', artist: 'Nirvana' },
  { title: 'Crazy Little Thing Called Love', artist: 'Queen' },
  { title: 'Crossroads', artist: 'Eric Clapton' },
  { title: 'Dancing in the Moonlight', artist: 'King Harvest' },
  { title: 'Don\'t Dream It\'s Over', artist: 'Crowded House' },
  { title: 'Don\'t You Forget About Me', artist: 'Simple Minds' },
  { title: 'Drift Away', artist: 'Dobie Gray' },
  { title: 'Drops of Jupiter', artist: 'Train' },
  { title: 'Eminence Front', artist: 'The Who' },
  { title: 'End of the Line', artist: 'Traveling Wilburys' },
  { title: 'Everybody Wants to Rule the World', artist: 'Tears For Fears' },
  { title: 'Fishin\' in the Dark', artist: 'Nitty Gritty Dirt Band' },
  { title: 'Folsom Prison Blues', artist: 'Johnny Cash' },
  { title: 'Friends in Low Places', artist: 'Garth Brooks' },
  { title: 'Gimme All Your Lovin\'', artist: 'ZZ Top' },
  { title: 'Give Me One Reason', artist: 'Tracy Chapman' },
  { title: 'God Bless the USA', artist: 'Lee Greenwood' },
  { title: 'Gold on the Ceiling', artist: 'The Black Keys' },
  { title: 'Got My Mind Set on You', artist: 'George Harrison' },
  { title: 'Green River', artist: 'Creedence Clearwater Revival' },
  { title: 'Hard to Handle', artist: 'The Black Crowes' },
  { title: 'Harvest Moon', artist: 'Neil Young' },
  { title: 'Have You Ever Seen the Rain', artist: 'Creedence Clearwater Revival' },
  { title: 'Heartbreak Hotel', artist: 'Elvis Presley' },
  { title: 'Hey Hey What Can I Do', artist: 'Led Zeppelin' },
  { title: 'Honky Tonk Women', artist: 'The Rolling Stones' },
  { title: 'House of the Rising Sun', artist: 'The Animals' },
  { title: 'How Sweet It Is', artist: 'James Taylor' },
  { title: 'Howlin\' for You', artist: 'The Black Keys' },
  { title: 'How\'s It Going to Be', artist: 'Third Eye Blind' },
  { title: 'Hurts So Good', artist: 'John Mellencamp' },
  { title: 'I Melt with You', artist: 'Modern English' },
  { title: 'If You Could Only See', artist: 'Tonic' },
  { title: 'Inside Out', artist: 'Eve 6' },
  { title: 'Island in the Sun', artist: 'Weezer' },
  { title: 'Jack and Diane', artist: 'John Mellencamp' },
  { title: 'Jumpin\' Jack Flash', artist: 'The Rolling Stones' },
  { title: 'Kodachrome', artist: 'Paul Simon' },
  { title: 'Learn to Fly', artist: 'Foo Fighters' },
  { title: 'Learning to Fly', artist: 'Tom Petty & The Heartbreakers' },
  { title: 'Listen to the Music', artist: 'The Doobie Brothers' },
  { title: 'Little Lion Man', artist: 'Mumford & Sons' },
  { title: 'Lonely Boy', artist: 'The Black Keys' },
  { title: 'Mary Jane\'s Last Dance', artist: 'Tom Petty & The Heartbreakers' },
  { title: 'Me and Julio Down by the Schoolyard', artist: 'Paul Simon' },
  { title: 'Message in a Bottle', artist: 'The Police' },
  { title: 'Money', artist: 'Pink Floyd' },
  { title: 'Money for Nothing', artist: 'Dire Straits' },
  { title: 'Norwegian Wood', artist: 'The Beatles' },
  { title: 'Nose on the Grindstone', artist: 'Tyler Childers' },
  { title: 'I Am a Man of Constant Sorrow', artist: 'Soggy Bottom Boys' },
  { title: 'Paint It Black', artist: 'The Rolling Stones' },
  { title: 'Pawn Shop', artist: 'Sublime' },
  { title: 'Peaceful Easy Feeling', artist: 'Eagles' },
  { title: 'Pride and Joy', artist: 'Stevie Ray Vaughan' },
  { title: 'Proud Mary', artist: 'Creedence Clearwater Revival' },
  { title: 'Ramblin\' Man', artist: 'The Allman Brothers Band' },
  { title: 'Ring of Fire', artist: 'Johnny Cash' },
  { title: 'Rock the Casbah', artist: 'The Clash' },
  { title: 'Rocky Mountain Way', artist: 'Joe Walsh' },
  { title: 'Runnin\' Down a Dream', artist: 'Tom Petty' },
  { title: 'Say It Ain\'t So', artist: 'Weezer' },
  { title: 'Sharp Dressed Man', artist: 'ZZ Top' },
  { title: 'Should I Stay or Should I Go', artist: 'The Clash' },
  { title: 'Sleeping on the Blacktop', artist: 'Colter Wall' },
  { title: 'SOB', artist: 'Nathaniel Rateliff' },
  { title: 'Someday', artist: 'Sugar Ray' },
  { title: 'Something in the Orange', artist: 'Zach Bryan' },
  { title: 'Start Me Up', artist: 'The Rolling Stones' },
  { title: 'Stuck in the Middle with You', artist: 'Stealers Wheel' },
  { title: 'Sundown', artist: 'Gordon Lightfoot' },
  { title: 'Sweet Caroline', artist: 'Neil Diamond' },
  { title: 'Take It Easy', artist: 'Eagles' },
  { title: 'Take Me Home Country Roads', artist: 'John Denver' },
  { title: 'Take on Me', artist: 'a-ha' },
  { title: 'Takin\' Care of Business', artist: 'Bachman-Turner Overdrive' },
  { title: 'Tennessee Whiskey', artist: 'Chris Stapleton' },
  { title: 'Tequila Sunrise', artist: 'Eagles' },
  { title: 'Thank You', artist: 'Led Zeppelin' },
  { title: 'The Man Who Sold the World', artist: 'Nirvana' },
  { title: 'The Middle', artist: 'Jimmy Eat World' },
  { title: 'The Power of Love', artist: 'Huey Lewis & The News' },
  { title: 'The Stake', artist: 'Steve Miller Band' },
  { title: 'The Way', artist: 'Fastball' },
  { title: 'The Weight', artist: 'The Band' },
  { title: 'These Boots Are Made for Walkin\'', artist: 'Nancy Sinatra' },
  { title: 'Tighten Up', artist: 'The Black Keys' },
  { title: 'Time', artist: 'Pink Floyd' },
  { title: 'Two Princes', artist: 'Spin Doctors' },
  { title: 'Wanted Dead or Alive', artist: 'Bon Jovi' },
  { title: 'What I Like About You', artist: 'The Romantics' },
  { title: 'What\'s Your Name', artist: 'Lynyrd Skynyrd' },
  { title: 'When I Come Around', artist: 'Green Day' },
  { title: 'When the Levee Breaks', artist: 'Led Zeppelin' },
  { title: 'Whitehouse Road', artist: 'Tyler Childers' },
  { title: 'Who\'ll Stop the Rain', artist: 'Creedence Clearwater Revival' },
  { title: 'Wild Horses', artist: 'The Rolling Stones' },
  { title: 'Wish You Were Here', artist: 'Pink Floyd' },
  { title: 'You Wreck Me', artist: 'Tom Petty' },
  // New additions
  { title: 'Free Fallin\'', artist: 'Tom Petty' },
  { title: 'Hotel California', artist: 'Eagles' },
  { title: 'Desperado', artist: 'Eagles' },
  { title: 'Simple Man', artist: 'Lynyrd Skynyrd' },
  { title: 'Sweet Home Alabama', artist: 'Lynyrd Skynyrd' },
  { title: 'Brown Eyed Girl', artist: 'Van Morrison' },
  { title: 'Wonderful Tonight', artist: 'Eric Clapton' },
  { title: 'Layla', artist: 'Eric Clapton' },
  { title: 'Old Time Rock and Roll', artist: 'Bob Seger' },
  { title: 'Turn the Page', artist: 'Bob Seger' },
  { title: 'The Joker', artist: 'Steve Miller Band' },
  { title: 'Sultans of Swing', artist: 'Dire Straits' },
  { title: 'Midnight Rider', artist: 'The Allman Brothers Band' },
  { title: 'Knockin\' on Heaven\'s Door', artist: 'Bob Dylan' },
  { title: 'American Pie', artist: 'Don McLean' },
  { title: 'Heart of Gold', artist: 'Neil Young' },
  { title: 'Into the Mystic', artist: 'Van Morrison' },
  { title: 'Moondance', artist: 'Van Morrison' },
  { title: 'Lyin\' Eyes', artist: 'Eagles' },
  { title: 'I Won\'t Back Down', artist: 'Tom Petty' },
  { title: 'Blackbird', artist: 'The Beatles' },
  { title: 'Let It Be', artist: 'The Beatles' },
  { title: 'Here Comes the Sun', artist: 'The Beatles' },
  { title: 'Come Together', artist: 'The Beatles' },
  { title: 'Yesterday', artist: 'The Beatles' },
  { title: 'Hey Jude', artist: 'The Beatles' },
  { title: 'Wonderwall', artist: 'Oasis' },
  { title: 'Everlong', artist: 'Foo Fighters' },
  { title: 'Times Like These', artist: 'Foo Fighters' },
  { title: 'Daughter', artist: 'Pearl Jam' },
  { title: 'Just Breathe', artist: 'Pearl Jam' },
  { title: 'Semi-Charmed Life', artist: 'Third Eye Blind' },
  { title: 'Jumper', artist: 'Third Eye Blind' },
  { title: 'Iris', artist: 'Goo Goo Dolls' },
  { title: 'Closing Time', artist: 'Semisonic' },
  { title: 'What I Got', artist: 'Sublime' },
  { title: 'Santeria', artist: 'Sublime' },
  { title: 'Otherside', artist: 'Red Hot Chili Peppers' },
  { title: 'Under the Bridge', artist: 'Red Hot Chili Peppers' },
  { title: 'Californication', artist: 'Red Hot Chili Peppers' },
  { title: 'Drive', artist: 'Incubus' },
  { title: 'Aqueous Transmission', artist: 'Incubus' },
  { title: 'Pardon Me', artist: 'Incubus' },
  { title: 'Warning', artist: 'Incubus' },
  { title: 'Black Hole Sun', artist: 'Soundgarden' },
  { title: 'I Am the Highway', artist: 'Audioslave' },
  { title: 'Plush', artist: 'Stone Temple Pilots' },
  { title: 'Good Riddance (Time of Your Life)', artist: 'Green Day' },
  { title: 'Yellow', artist: 'Coldplay' },
  { title: 'The Scientist', artist: 'Coldplay' },
  { title: 'Clocks', artist: 'Coldplay' },
  { title: 'Man on the Moon', artist: 'R.E.M.' },
  { title: 'Losing My Religion', artist: 'R.E.M.' },
  { title: 'Crash Into Me', artist: 'Dave Matthews Band' },
  { title: 'Shine', artist: 'Collective Soul' },
  { title: 'Little Talks', artist: 'Of Monsters and Men' },
  { title: 'Better Together', artist: 'Jack Johnson' },
  { title: 'Banana Pancakes', artist: 'Jack Johnson' },
  { title: 'Flake', artist: 'Jack Johnson' },
  { title: 'Wagon Wheel', artist: 'Old Crow Medicine Show' },
  { title: 'Thunder Rolls', artist: 'Garth Brooks' },
  { title: 'Neon Moon', artist: 'Brooks & Dunn' },
  { title: 'Devil Went Down to Georgia', artist: 'Charlie Daniels Band' },
  { title: 'On the Road Again', artist: 'Willie Nelson' },
  { title: 'Jolene', artist: 'Dolly Parton' },
  { title: 'All Your\'n', artist: 'Tyler Childers' },
  { title: 'Margaritaville', artist: 'Jimmy Buffett' },
  { title: 'The Thrill Is Gone', artist: 'B.B. King' },
  { title: 'Sweet Home Chicago', artist: 'Blues Standard' },
  { title: 'Born Under a Bad Sign', artist: 'Albert King' },
  { title: 'Stormy Monday', artist: 'T-Bone Walker' },
  { title: 'Red House', artist: 'Jimi Hendrix' },
  { title: 'All Along the Watchtower', artist: 'Jimi Hendrix' },
  { title: 'Dock of the Bay', artist: 'Otis Redding' },
  { title: 'Ain\'t No Sunshine', artist: 'Bill Withers' },
  { title: 'Use Me', artist: 'Bill Withers' },
  { title: 'Lovely Day', artist: 'Bill Withers' },
  { title: 'Lean on Me', artist: 'Bill Withers' },
  { title: 'Stand By Me', artist: 'Ben E. King' },
  { title: 'Superstition', artist: 'Stevie Wonder' },
  { title: 'Gravity', artist: 'John Mayer' },
  { title: 'Fire and Rain', artist: 'James Taylor' },
  { title: 'Carolina in My Mind', artist: 'James Taylor' },
  { title: 'Southern Cross', artist: 'Crosby, Stills & Nash' },
  { title: 'Can\'t You See', artist: 'Marshall Tucker Band' },
  { title: 'A Horse with No Name', artist: 'America' },
  { title: 'Ventura Highway', artist: 'America' },
  { title: 'For What It\'s Worth', artist: 'Buffalo Springfield' },
  { title: 'Go Your Own Way', artist: 'Fleetwood Mac' },
  { title: 'Patience', artist: 'Guns N\' Roses' },
  { title: 'Jessie\'s Girl', artist: 'Rick Springfield' },
  { title: 'Suspicious Minds', artist: 'Elvis Presley' },
  { title: 'Can\'t Help Falling in Love', artist: 'Elvis Presley' },
  { title: 'Ho Hey', artist: 'The Lumineers' },
  { title: 'Riptide', artist: 'Vance Joy' },
  { title: 'I\'m Yours', artist: 'Jason Mraz' },
  { title: 'Skinny Love', artist: 'Bon Iver' },
  { title: 'Hold My Hand', artist: 'Hootie & the Blowfish' },
  { title: 'Angel from Montgomery', artist: 'John Prine' },
  { title: 'Breakdown', artist: 'Tom Petty' },
  { title: 'Chattahoochee', artist: 'Alan Jackson' },
  { title: 'Comfortably Numb', artist: 'Pink Floyd' },
  { title: 'Deeper Than the Holler', artist: 'Randy Travis' },
  { title: 'Down on the Corner', artist: 'Creedence Clearwater Revival' },
  { title: 'Dreams', artist: 'Fleetwood Mac' },
  { title: 'Hallelujah', artist: 'Jeff Buckley' },
  { title: 'Hey There Delilah', artist: 'Plain White T\'s' },
  { title: 'Jamming', artist: 'Bob Marley' },
  { title: 'Keep Your Hands to Yourself', artist: 'Georgia Satellites' },
  { title: 'Lovesong', artist: 'The Cure' },
  { title: 'Piano Man', artist: 'Billy Joel' },
  { title: 'Ramble On', artist: 'Led Zeppelin' },
  { title: 'Runaround', artist: 'Blues Traveler' },
  { title: 'Three Little Birds', artist: 'Bob Marley' },
  { title: 'Tuesday\'s Gone', artist: 'Lynyrd Skynyrd' },
  { title: 'Wicked Game', artist: 'Chris Isaak' },
].sort((a, b) => a.title.localeCompare(b.title))
